version: '3'
services:
  rabbitmq3:
    image: rabbitmq:3-management-alpine
    build:  ./rabbitMq/
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret cookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBUTMQ_DEFAULT_PASS: "guest"
    ports:
      - 15672:15672
      - 5672:5672
    #host : container
    #5672:5672 means that port 5672 on host will forward all its traffic
    # to RabbitMQ's main port 5672 in the container. 
    # Same with management plugin's port 15672:15672.

  index:
    build:  ./
    ports: ['8080:8080']
